version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: neptunebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/neptunebank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    networks:
      - app-network
    depends_on:
      - inventory-service
    ports:
      - "8084:8084"

  frontend:
    build:
      context: ./order-processing-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - order-service
      - inventory-service

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
